export const seedEstablishments = [
  { id: "seed-1", name: "Hambúrgueria do Beto", category: "Hamburgueria", bairro: "Centro", status: "aprovado",
    scoreSum: 92, scoreCount: 10, address: "Rua dos Andradas, 540 - Centro", phone: "(51) 3225-4410",
    instagram: "@hamburgueriadobeto", tags: ["Bom para ir em grupo", "Atendimento rápido"],
    promos: [{ id: "promo-1", title: "Terça é dia de dobro", desc: "Compre 1 lanche e leve 2 na terça-feira", until: "30/09/2026" }] },
  { id: "seed-2", name: "Sushi Kaito", category: "Japonês", bairro: "Moinhos", status: "aprovado",
    scoreSum: 87, scoreCount: 10, address: "Rua Padre Chagas, 88 - Moinhos de Vento", phone: "(51) 3346-2290",
    instagram: "@sushikaito", tags: [], promos: [] },
  { id: "seed-3", name: "Pizzaria Napoli", category: "Pizzaria", bairro: "Floresta", status: "aprovado",
    scoreSum: 95, scoreCount: 10, address: "Av. Cristóvão Colombo, 1200 - Floresta", phone: "(51) 3311-7788",
    instagram: "@pizzarianapoli.poa", tags: ["Boa opção para delivery"], promos: [] },
  { id: "seed-4", name: "Café da Vó", category: "Cafeteria", bairro: "Bom Fim", status: "aprovado",
    scoreSum: 89, scoreCount: 10, address: "Rua João Alfredo, 320 - Bom Fim", phone: "(51) 3222-1156",
    instagram: "@cafedavopoa", tags: [], promos: [] },
  { id: "seed-5", name: "Boteco do Zé", category: "Comida brasileira", bairro: "Cidade Baixa", status: "aprovado",
    scoreSum: 84, scoreCount: 10, address: "Rua João Alfredo, 720 - Cidade Baixa", phone: "(51) 3212-9034",
    instagram: null, tags: [], promos: [] },
  { id: "seed-6", name: "Doceria Flor de Mel", category: "Doceria", bairro: "Petrópolis", status: "aprovado",
    scoreSum: 91, scoreCount: 10, address: "Av. Cel. Lucas de Oliveira, 95 - Petrópolis", phone: "(51) 3339-4471",
    instagram: "@flordemeldoceria", tags: ["Ambiente agradável"], promos: [] },
  { id: "seed-7", name: "Sabor Oriental", category: "Japonês", bairro: "Centro", status: "aprovado",
    scoreSum: 78, scoreCount: 10, address: "Rua dos Andradas, 1230 - Centro", phone: "(51) 3224-6602",
    instagram: "@sabororientalpoa", tags: [], promos: [] },
  { id: "seed-8", name: "Hamburgueria Rústica", category: "Hamburgueria", bairro: "Auxiliadora", status: "aprovado",
    scoreSum: 82, scoreCount: 10, address: "Rua Mostardeiro, 220 - Auxiliadora", phone: "(51) 3029-8845",
    instagram: null, tags: [], promos: [] },
  { id: "seed-101", name: "Espaço Verde Vegano", category: "Comida brasileira", bairro: "Bela Vista", status: "pendente",
    scoreSum: 9, scoreCount: 1, address: "", phone: "", instagram: null, tags: [], promos: [] },
  { id: "seed-102", name: "Hot Dog do Marcão", category: "Hamburgueria", bairro: "Centro", status: "pendente",
    scoreSum: 17, scoreCount: 2, address: "", phone: "", instagram: null, tags: [], promos: [] },
];

export const seedReviews = [
  { id: "rev-1", establishmentId: "seed-1", author: "Ana", score: 10, comment: "Melhor smash burger da cidade, sem dúvida.", tags: [], flagged: false, flagReason: null },
  { id: "rev-2", establishmentId: "seed-1", author: "Rafael", score: 9, comment: "Ambiente simples, mas o lanche compensa.", tags: [], flagged: false, flagReason: null },
  { id: "rev-3", establishmentId: "seed-2", author: "Camila", score: 9, comment: "Peixe muito fresco, voltarei sempre.", tags: [], flagged: false, flagReason: null },
  { id: "rev-4", establishmentId: "seed-2", author: "Diego", score: 8, comment: "Preço justo pela qualidade.", tags: [], flagged: false, flagReason: null },
  { id: "rev-5", establishmentId: "seed-3", author: "Bruno", score: 10, comment: "Massa perfeita, borda crocante.", tags: [], flagged: false, flagReason: null },
  { id: "rev-6", establishmentId: "seed-3", author: "Larissa", score: 9, comment: "Entrega rápida e quentinha.", tags: [], flagged: false, flagReason: null },
  { id: "rev-7", establishmentId: "seed-4", author: "Juliana", score: 9, comment: "Bolo de fubá igual ao da minha avó.", tags: [], flagged: false, flagReason: null },
  { id: "rev-8", establishmentId: "seed-4", author: "Marcos", score: 9, comment: "Café coado impecável.", tags: [], flagged: false, flagReason: null },
  { id: "rev-9", establishmentId: "seed-5", author: "Patrícia", score: 8, comment: "Feijoada de domingo é imbatível.", tags: [], flagged: false, flagReason: null },
  { id: "rev-10", establishmentId: "seed-5", author: "Thiago", score: 9, comment: "Porções generosas, preço justo.", tags: [], flagged: false, flagReason: null },
  { id: "rev-11", establishmentId: "seed-6", author: "Vanessa", score: 9, comment: "Brigadeiro gourmet vale cada centavo.", tags: [], flagged: false, flagReason: null },
  { id: "rev-12", establishmentId: "seed-6", author: "Eduardo", score: 9, comment: "Embalagem linda para presente.", tags: [], flagged: false, flagReason: null },
  { id: "rev-13", establishmentId: "seed-7", author: "Renata", score: 8, comment: "Bom custo-benefício no rodízio.", tags: [], flagged: false, flagReason: null },
  { id: "rev-14", establishmentId: "seed-7", author: "Felipe", score: 7, comment: "Atendimento poderia ser mais ágil.", tags: [], flagged: false, flagReason: null },
  { id: "rev-15", establishmentId: "seed-8", author: "Gabriela", score: 8, comment: "Pão brioche caseiro faz diferença.", tags: [], flagged: false, flagReason: null },
  { id: "rev-16", establishmentId: "seed-8", author: "Lucas", score: 8, comment: "Batata rústica é o ponto alto.", tags: [], flagged: false, flagReason: null },
  { id: "rev-101", establishmentId: "seed-101", author: "Você", score: 9, comment: "", tags: [], flagged: false, flagReason: null },
  { id: "rev-102a", establishmentId: "seed-102", author: "Você", score: 8, comment: "", tags: [], flagged: false, flagReason: null },
  { id: "rev-102b", establishmentId: "seed-102", author: "Marina", score: 9, comment: "", tags: [], flagged: false, flagReason: null },
  { id: "rev-flag-1", establishmentId: "seed-5", author: "usuário anônimo", score: 0, comment: "Comentário removido pelo filtro automático por linguagem inadequada.", tags: [], flagged: true, flagReason: "Linguagem inadequada" },
  { id: "rev-flag-2", establishmentId: "seed-2", author: "conta_nova_123", score: 10, comment: "Mesma conta avaliou 8 lugares em 2 minutos — padrão típico de avaliação em massa.", tags: [], flagged: true, flagReason: "Possível avaliação falsa" },
];

export const seedLists = [
  { id: "list-201", name: "Rolê de sexta", members: ["Você", "Marina"], placeIds: ["seed-3", "seed-1"], visited: ["seed-1"] },
  { id: "list-202", name: "Descobertas com a galera", members: ["Você", "Rafa", "Bia", "João"], placeIds: ["seed-2", "seed-6", "seed-5"], visited: [] },
];
